name: Enforce PR tasks are completed

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  task-check:
    runs-on: ubuntu-latest
    name: Enforce PR tasks are completed
    steps:
      - uses: venkatsarvesh/pr-tasks-completed-action@ca10aff169d4f8b3c9f5ee7b3ae56b7fe31391b0 # v1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
