name: Enforce PR labels

on:
  pull_request:
    types:
      - edited
      - opened
      - labeled
      - unlabeled
      - reopened
      - synchronize

jobs:
  enforce-label:
    runs-on: ubuntu-latest
    name: Enforce PR labels
    steps:
      - uses: yogevbd/enforce-label-action@8d1e1709b1011e6d90400a0e6cf7c0b77aa5efeb # 2.1.0
        with:
          REQUIRED_LABELS_ANY: "build,ci,docs,feat,fix,perf,refactor,style,test"
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label in ['build','ci','docs','feat','fix','perf','refactor','style','test']"
          BANNED_LABELS: "duplicate,question,experiment"
